//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManager.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribucion
    {
        public int Id { get; set; }
        public Nullable<int> ccdepcve { get; set; }
        public int ccpercve { get; set; }
        public Nullable<int> ccpertar { get; set; }
        public string ccpernom { get; set; }
        public string cccve { get; set; }
        public int cchrst { get; set; }
        public int ccdes { get; set; }
        public int cceso { get; set; }
        public int ccnmat { get; set; }
        public int ccmath { get; set; }
        public int ccexc { get; set; }
        public string ccmot { get; set; }
        public Nullable<System.DateTime> ccperara { get; set; }
        public string cctitnco { get; set; }
        public Nullable<int> ccesrced { get; set; }
        public int cccar1a { get; set; }
        public int cccar1b { get; set; }
        public int cccar2a { get; set; }
        public int cccar2b { get; set; }
        public int cccar3a { get; set; }
        public int cccar3b { get; set; }
        public int cccar4a { get; set; }
        public int cccar4b { get; set; }
        public int cccar5a { get; set; }
        public int cccar5b { get; set; }
        public int cccar6a { get; set; }
        public int cccar6b { get; set; }
        public int cccar7a { get; set; }
        public int cccar7b { get; set; }
        public int cccar8a { get; set; }
        public int cccar8b { get; set; }
        public int cccar9a { get; set; }
        public int cccar9b { get; set; }
        public int cccar10a { get; set; }
        public int cccar10b { get; set; }
        public int ccpdo1a { get; set; }
        public int ccpdo1b { get; set; }
        public int ccpdo2a { get; set; }
        public int ccpdo2b { get; set; }
        public int ccpdo3a { get; set; }
        public int ccpdo3b { get; set; }
        public int ccpdo4a { get; set; }
        public int ccpdo4b { get; set; }
        public int ccpdo5a { get; set; }
        public int ccpdo5b { get; set; }
        public int ccpdo6a { get; set; }
        public int ccpdo6b { get; set; }
        public int ccpdo7a { get; set; }
        public int ccpdo7b { get; set; }
        public int ccpdo8a { get; set; }
        public int ccpdo8b { get; set; }
        public int ccpdo9a { get; set; }
        public int ccpdo9b { get; set; }
        public int ccpdo10a { get; set; }
        public int ccpdo10b { get; set; }
        public string fecha { get; set; }
    }
}
