//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManager.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estructura
    {
        public int Id { get; set; }
        public Nullable<int> ccdepcve { get; set; }
        public int ccpercve { get; set; }
        public int ccpertar { get; set; }
        public string ccpernom { get; set; }
        public int ccplmcve { get; set; }
        public Nullable<System.DateTime> ccperara { get; set; }
        public string cccatcve { get; set; }
        public int ccplmhrs { get; set; }
        public int cchfglic { get; set; }
        public int cchgpos { get; set; }
        public int ccdes { get; set; }
        public Nullable<bool> ccfac { get; set; }
        public string ccmot { get; set; }
        public string ccmatcve { get; set; }
        public string ccmatnco { get; set; }
        public int ccmathte { get; set; }
        public int ccmathpr { get; set; }
        public int ccngp { get; set; }
        public string cccarnco { get; set; }
        public string cctitnco { get; set; }
        public Nullable<int> ccesrced { get; set; }
        public string ccperrfc { get; set; }
        public string ccacdnco { get; set; }
        public int ccacdhrs { get; set; }
        public string ccmatnom { get; set; }
    }
}
