//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManager.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public Nullable<int> ccdepcve { get; set; }
        public Nullable<int> ccperdepa { get; set; }
        public int ccpercve { get; set; }
        public int ccpertar { get; set; }
        public string ccpernom { get; set; }
        public Nullable<System.DateTime> ccperara { get; set; }
        public string cctitnco { get; set; }
        public Nullable<int> ccesrced { get; set; }
        public string ccperrfc { get; set; }
    }
}
