//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManager.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalFrenteAGrupo
    {
        public int Id { get; set; }
        public Nullable<int> ccdepcve { get; set; }
        public int ccpercve { get; set; }
        public Nullable<int> ccpertar { get; set; }
        public string ccpernom { get; set; }
        public string cccve { get; set; }
        public int cchrst { get; set; }
        public int ccdes { get; set; }
        public int cceso { get; set; }
        public int ccmat { get; set; }
        public int ccnmat { get; set; }
        public int ccmath { get; set; }
        public int ccexc { get; set; }
        public string ccmot { get; set; }
    }
}
