//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManager.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public int id_cuenta { get; set; }
        public string contraseña_usuarios { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
